version: 2
before:
  hooks:
    - ./scripts/completions.sh
    - ./scripts/manpages.sh

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - freebsd
      - linux
      - solaris
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
      - mips64
      - mips64le
      - ppc64
      - ppc64le
      - riscv64
      - s390x
    goarm:
      - 5
      - 6
      - 7
    gomips:
      - softfloat
    ignore:
      - goos: windows
        goarch: arm
    flags:
      - -trimpath
    ldflags:
      - "-s -w -X github.com/prometheus/common/version.Version={{.Version}} -X github.com/prometheus/common/version.BuildDate={{.Date}} -X github.com/prometheus/common/version.Branch={{.Branch}} -X github.com/prometheus/common/version.BuildUser=goreleaser"

changelog:
  disable: true

archives:
  - format_overrides:
      - goos: windows
        formats: ['zip']
    files:
      - README.md
      - LICENSE
      - completions/*
      - manpages/*

sboms:
  - artifacts: archive
    documents:
      - "${artifact}.spdx.json"

signs:
  - cmd: cosign
    artifacts: checksum
    output: true
    certificate: "${artifact}.pem"
    args:
      - sign-blob
      - "--output-signature=${signature}"
      - "--output-certificate=${certificate}"
      - "${artifact}"
      - "--yes"

milestones:
  - close: true

homebrew_casks:
  - repository:
      owner: nginx
      name: homebrew-tap
      token: "{{ .Env.NGINX_GITHUB_TOKEN }}"
    directory: Casks
    homepage: https://github.com/nginx/nginx-prometheus-exporter
    description: NGINX Prometheus Exporter for NGINX and NGINX Plus
    commit_author:
      name: nginx-bot
      email: integrations@nginx.com
    manpages:
      - "manpages/nginx-prometheus-exporter.1.gz"
    completions:
      bash: "completions/nginx-prometheus-exporter.bash"
      zsh: "completions/nginx-prometheus-exporter.zsh"

nix:
  - name: nginx-prometheus-exporter
    repository:
      owner: nginx
      name: nur
      token: "{{ .Env.NGINX_GITHUB_TOKEN }}"
    homepage: https://github.com/nginx/nginx-prometheus-exporter
    description: NGINX Prometheus Exporter for NGINX and NGINX Plus
    license: asl20
    commit_author:
      name: nginx-bot
      email: integrations@nginx.com
    extra_install: |-
      installManPage ./manpages/nginx-prometheus-exporter.1.gz
      installShellCompletion ./completions/*

scoops:
  - repository:
      owner: nginx
      name: scoop-bucket
      token: "{{ .Env.NGINX_GITHUB_TOKEN }}"
    directory: bucket
    homepage: https://github.com/nginx/nginx-prometheus-exporter
    description: NGINX Prometheus Exporter for NGINX and NGINX Plus
    license: Apache-2.0
    commit_author:
      name: nginx-bot
      email: integrations@nginx.com
